### ISSUE TITLE
UNC path for ifc selection not working

### ISSUE THREAD

**Issue by mucfun** [agnBIM/ifc2room#2]
getestet mit verschiedenen ifc Dateien unter Revit 2022.1
![agn](https://user-images.githubusercontent.com/94551299/146163935-a53fe22f-4a05-42e0-af52-19d99fbd8422.jpg)

**Comment by agnBIM** [comment]
Um auch internationalen Nutzern einen Einblick in das Issue zu ermöglichen haben wir die Antwort in Englisch verfasst:

The problem will probably be due to the use of UNC paths.
At least that is how we could reproduce it.

These are currently not supported by the application. Currently only paths with prefixed drive names can be used.

We will put it on the agenda and include it in the next version at the latest.

Please let us know if the problem is solved for you or persists.
